// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bussijaama_haaldus_projekt_u2_api.Data;

#nullable disable

namespace bussijaamahaaldusprojektu2api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210210001_Seed30Routes")]
    partial class Seed30Routes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("bussijaama_haaldus_projekt_u2_api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "57ad57d1-ff50-4501-8cce-8c1c70730a75",
                            Email = "admin@bussijaam.ee",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BUSSIJAAM.EE",
                            NormalizedUserName = "ADMIN@BUSSIJAAM.EE",
                            PasswordHash = "AQAAAAIAAYagAAAAEAYkdX+yZyJDi1IVLJCnvp/0mDcslvJjX7X+L0PqhN76A82fH5qCnK8CyNCDf3d1jg==",
                            PhoneNumberConfirmed = true,
                            RegisteredAt = new DateTime(2025, 12, 10, 21, 0, 0, 708, DateTimeKind.Utc).AddTicks(5790),
                            SecurityStamp = "c5ef0099-9916-4f80-9597-8db044ac6187",
                            TwoFactorEnabled = false,
                            UserName = "admin@bussijaam.ee"
                        });
                });

            modelBuilder.Entity("bussijaama_haaldus_projekt_u2_api.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartureStation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DestinationStation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(2025, 12, 8, 20, 15, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 8, 18, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tartu",
                            DestinationStation = "Tartu Bus Station",
                            Number = "BUS-2515",
                            Price = 13.16m
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2025, 12, 11, 21, 31, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 11, 19, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tartu",
                            DestinationStation = "Tartu Bus Station",
                            Number = "BUS-7850",
                            Price = 10.71m
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new DateTime(2025, 12, 9, 16, 30, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 9, 14, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tartu",
                            DestinationStation = "Tartu Bus Station",
                            Number = "BUS-4428",
                            Price = 11.74m
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new DateTime(2025, 12, 11, 2, 11, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tartu",
                            DestinationStation = "Tartu Bus Station",
                            Number = "BUS-6194",
                            Price = 15.20m
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new DateTime(2025, 12, 9, 9, 13, 0, 0, DateTimeKind.Local),
                            Company = "Baltic Shuttle",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 9, 7, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tartu",
                            DestinationStation = "Tartu Bus Station",
                            Number = "BUS-8344",
                            Price = 14.44m
                        },
                        new
                        {
                            Id = 6,
                            ArrivalTime = new DateTime(2025, 12, 11, 16, 36, 0, 0, DateTimeKind.Local),
                            Company = "Baltic Shuttle",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 11, 15, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Pärnu",
                            DestinationStation = "Pärnu Bus Station",
                            Number = "BUS-7232",
                            Price = 13.35m
                        },
                        new
                        {
                            Id = 7,
                            ArrivalTime = new DateTime(2025, 12, 9, 3, 31, 0, 0, DateTimeKind.Local),
                            Company = "FlixBus",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 9, 2, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Pärnu",
                            DestinationStation = "Pärnu Bus Station",
                            Number = "BUS-6247",
                            Price = 9.16m
                        },
                        new
                        {
                            Id = 8,
                            ArrivalTime = new DateTime(2025, 12, 8, 8, 51, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 8, 7, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Pärnu",
                            DestinationStation = "Pärnu Bus Station",
                            Number = "BUS-7734",
                            Price = 12.64m
                        },
                        new
                        {
                            Id = 9,
                            ArrivalTime = new DateTime(2025, 12, 8, 6, 22, 0, 0, DateTimeKind.Local),
                            Company = "Lux Express",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 8, 4, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Narva",
                            DestinationStation = "Narva Bus Station",
                            Number = "BUS-6637",
                            Price = 13.47m
                        },
                        new
                        {
                            Id = 10,
                            ArrivalTime = new DateTime(2025, 12, 9, 12, 51, 0, 0, DateTimeKind.Local),
                            Company = "Lux Express",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 9, 10, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Narva",
                            DestinationStation = "Narva Bus Station",
                            Number = "BUS-6832",
                            Price = 10.03m
                        },
                        new
                        {
                            Id = 11,
                            ArrivalTime = new DateTime(2025, 12, 8, 14, 44, 0, 0, DateTimeKind.Local),
                            Company = "Baltic Shuttle",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 8, 12, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Narva",
                            DestinationStation = "Narva Bus Station",
                            Number = "BUS-1457",
                            Price = 11.61m
                        },
                        new
                        {
                            Id = 12,
                            ArrivalTime = new DateTime(2025, 12, 11, 7, 8, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 11, 5, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Viljandi",
                            DestinationStation = "Viljandi Bus Station",
                            Number = "BUS-4286",
                            Price = 10.09m
                        },
                        new
                        {
                            Id = 13,
                            ArrivalTime = new DateTime(2025, 12, 8, 14, 29, 0, 0, DateTimeKind.Local),
                            Company = "Lux Express",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 8, 12, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Viljandi",
                            DestinationStation = "Viljandi Bus Station",
                            Number = "BUS-5176",
                            Price = 10.49m
                        },
                        new
                        {
                            Id = 14,
                            ArrivalTime = new DateTime(2025, 12, 12, 9, 18, 0, 0, DateTimeKind.Local),
                            Company = "Lux Express",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 12, 7, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Viljandi",
                            DestinationStation = "Viljandi Bus Station",
                            Number = "BUS-5495",
                            Price = 13.59m
                        },
                        new
                        {
                            Id = 15,
                            ArrivalTime = new DateTime(2025, 12, 12, 16, 0, 0, 0, DateTimeKind.Local),
                            Company = "Ecolines",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 12, 14, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Viljandi",
                            DestinationStation = "Viljandi Bus Station",
                            Number = "BUS-1573",
                            Price = 10.02m
                        },
                        new
                        {
                            Id = 16,
                            ArrivalTime = new DateTime(2025, 12, 8, 19, 37, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 8, 17, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Viljandi",
                            DestinationStation = "Viljandi Bus Station",
                            Number = "BUS-5150",
                            Price = 16.51m
                        },
                        new
                        {
                            Id = 17,
                            ArrivalTime = new DateTime(2025, 12, 8, 8, 25, 0, 0, DateTimeKind.Local),
                            Company = "Ecolines",
                            DepartureCity = "Tartu",
                            DepartureStation = "Tartu Bus Station",
                            DepartureTime = new DateTime(2025, 12, 8, 6, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-4932",
                            Price = 10.49m
                        },
                        new
                        {
                            Id = 18,
                            ArrivalTime = new DateTime(2025, 12, 10, 22, 26, 0, 0, DateTimeKind.Local),
                            Company = "Baltic Shuttle",
                            DepartureCity = "Tartu",
                            DepartureStation = "Tartu Bus Station",
                            DepartureTime = new DateTime(2025, 12, 10, 20, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-9164",
                            Price = 11.58m
                        },
                        new
                        {
                            Id = 19,
                            ArrivalTime = new DateTime(2025, 12, 12, 1, 10, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Tartu",
                            DepartureStation = "Tartu Bus Station",
                            DepartureTime = new DateTime(2025, 12, 11, 23, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-9618",
                            Price = 15.68m
                        },
                        new
                        {
                            Id = 20,
                            ArrivalTime = new DateTime(2025, 12, 12, 1, 16, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Tartu",
                            DepartureStation = "Tartu Bus Station",
                            DepartureTime = new DateTime(2025, 12, 11, 23, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-5068",
                            Price = 10.22m
                        },
                        new
                        {
                            Id = 21,
                            ArrivalTime = new DateTime(2025, 12, 8, 19, 35, 0, 0, DateTimeKind.Local),
                            Company = "Baltic Shuttle",
                            DepartureCity = "Pärnu",
                            DepartureStation = "Pärnu Bus Station",
                            DepartureTime = new DateTime(2025, 12, 8, 18, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-6324",
                            Price = 8.51m
                        },
                        new
                        {
                            Id = 22,
                            ArrivalTime = new DateTime(2025, 12, 13, 5, 1, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Pärnu",
                            DepartureStation = "Pärnu Bus Station",
                            DepartureTime = new DateTime(2025, 12, 13, 3, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-7433",
                            Price = 11.71m
                        },
                        new
                        {
                            Id = 23,
                            ArrivalTime = new DateTime(2025, 12, 11, 3, 10, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Pärnu",
                            DepartureStation = "Pärnu Bus Station",
                            DepartureTime = new DateTime(2025, 12, 11, 1, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-1217",
                            Price = 11.56m
                        },
                        new
                        {
                            Id = 24,
                            ArrivalTime = new DateTime(2025, 12, 13, 3, 31, 0, 0, DateTimeKind.Local),
                            Company = "Lux Express",
                            DepartureCity = "Pärnu",
                            DepartureStation = "Pärnu Bus Station",
                            DepartureTime = new DateTime(2025, 12, 13, 2, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-3388",
                            Price = 8.54m
                        },
                        new
                        {
                            Id = 25,
                            ArrivalTime = new DateTime(2025, 12, 9, 16, 54, 0, 0, DateTimeKind.Local),
                            Company = "FlixBus",
                            DepartureCity = "Pärnu",
                            DepartureStation = "Pärnu Bus Station",
                            DepartureTime = new DateTime(2025, 12, 9, 15, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-1843",
                            Price = 9.95m
                        },
                        new
                        {
                            Id = 26,
                            ArrivalTime = new DateTime(2025, 12, 8, 16, 53, 0, 0, DateTimeKind.Local),
                            Company = "FlixBus",
                            DepartureCity = "Riga",
                            DepartureStation = "Riga Central Station",
                            DepartureTime = new DateTime(2025, 12, 8, 13, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-7759",
                            Price = 17.27m
                        },
                        new
                        {
                            Id = 27,
                            ArrivalTime = new DateTime(2025, 12, 8, 8, 41, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Riga",
                            DepartureStation = "Riga Central Station",
                            DepartureTime = new DateTime(2025, 12, 8, 5, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-9062",
                            Price = 20.89m
                        },
                        new
                        {
                            Id = 28,
                            ArrivalTime = new DateTime(2025, 12, 13, 3, 14, 0, 0, DateTimeKind.Local),
                            Company = "Ecolines",
                            DepartureCity = "Riga",
                            DepartureStation = "Riga Central Station",
                            DepartureTime = new DateTime(2025, 12, 12, 23, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-5907",
                            Price = 16.95m
                        },
                        new
                        {
                            Id = 29,
                            ArrivalTime = new DateTime(2025, 12, 9, 3, 52, 0, 0, DateTimeKind.Local),
                            Company = "NordBus",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Riga",
                            DestinationStation = "Riga Central Station",
                            Number = "BUS-1266",
                            Price = 16.28m
                        },
                        new
                        {
                            Id = 30,
                            ArrivalTime = new DateTime(2025, 12, 13, 0, 20, 0, 0, DateTimeKind.Local),
                            Company = "FlixBus",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 12, 12, 20, 0, 0, 0, DateTimeKind.Local),
                            DestinationCity = "Riga",
                            DestinationStation = "Riga Central Station",
                            Number = "BUS-2216",
                            Price = 20.47m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("bussijaama_haaldus_projekt_u2_api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("bussijaama_haaldus_projekt_u2_api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bussijaama_haaldus_projekt_u2_api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("bussijaama_haaldus_projekt_u2_api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
