// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bussijaama_haaldus_projekt_u2_api.Data;

#nullable disable

namespace bussijaamahaaldusprojektu2api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210085735_InitialWithFixedAdmi")]
    partial class InitialWithFixedAdmi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("bussijaama_haaldus_projekt_u2_api.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "46c86a67-615b-4ebc-9cc5-7398c5165667",
                            Email = "admin@bussijaam.ee",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@BUSSIJAAM.EE",
                            NormalizedUserName = "ADMIN@BUSSIJAAM.EE",
                            PasswordHash = "AQAAAAIAAYagAAAAECpSQip9fO9EdUwXck6tj5Aqkmg3ZtsRBXcs+KZuxah+n7sCUUUuz93hdOQznMXLFg==",
                            PhoneNumberConfirmed = true,
                            RegisteredAt = new DateTime(2025, 12, 10, 8, 57, 35, 626, DateTimeKind.Utc).AddTicks(1529),
                            SecurityStamp = "6b076daa-e55b-4262-b654-d4add206411e",
                            TwoFactorEnabled = false,
                            UserName = "admin@bussijaam.ee"
                        });
                });

            modelBuilder.Entity("bussijaama_haaldus_projekt_u2_api.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartureCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DepartureStation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestinationCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DestinationStation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(2025, 3, 10, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            Company = "NordBus",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 3, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationCity = "Tartu",
                            DestinationStation = "Tartu Bus Station",
                            Number = "BUS-1024",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(2025, 3, 10, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            Company = "NordBus",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 3, 10, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            DestinationCity = "Tartu",
                            DestinationStation = "Tartu Bus Station",
                            Number = "BUS-1024",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new DateTime(2025, 3, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Company = "Baltic Express",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 3, 11, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            DestinationCity = "Riga",
                            DestinationStation = "Riga Central Station",
                            Number = "BUS-2031",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new DateTime(2025, 3, 11, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            Company = "Baltic Express",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 3, 11, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            DestinationCity = "Riga",
                            DestinationStation = "Riga Central Station",
                            Number = "BUS-2031",
                            Price = 25.00m
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new DateTime(2025, 3, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Company = "EuroRoad",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 3, 12, 6, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationCity = "Vilnius",
                            DestinationStation = "Vilnius Bus Terminal",
                            Number = "BUS-3310",
                            Price = 35.50m
                        },
                        new
                        {
                            Id = 6,
                            ArrivalTime = new DateTime(2025, 3, 10, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Company = "Lux Express",
                            DepartureCity = "Tartu",
                            DepartureStation = "Tartu Bus Station",
                            DepartureTime = new DateTime(2025, 3, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-445",
                            Price = 12.50m
                        },
                        new
                        {
                            Id = 7,
                            ArrivalTime = new DateTime(2025, 3, 11, 17, 15, 0, 0, DateTimeKind.Unspecified),
                            Company = "Simple Express",
                            DepartureCity = "Riga",
                            DepartureStation = "Riga Central Station",
                            DepartureTime = new DateTime(2025, 3, 11, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationCity = "Tallinn",
                            DestinationStation = "Tallinn Bus Station",
                            Number = "BUS-778",
                            Price = 22.00m
                        },
                        new
                        {
                            Id = 8,
                            ArrivalTime = new DateTime(2025, 3, 13, 11, 20, 0, 0, DateTimeKind.Unspecified),
                            Company = "Lux Express",
                            DepartureCity = "Tallinn",
                            DepartureStation = "Tallinn Bus Station",
                            DepartureTime = new DateTime(2025, 3, 13, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            DestinationCity = "Pärnu",
                            DestinationStation = "Pärnu Bus Terminal",
                            Number = "BUS-990",
                            Price = 9.90m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("bussijaama_haaldus_projekt_u2_api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("bussijaama_haaldus_projekt_u2_api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("bussijaama_haaldus_projekt_u2_api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("bussijaama_haaldus_projekt_u2_api.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
